import coa_info
import doa_info
import access_info
import ip_assign



def connection_relation(network,project):
    connection_dict ={'mgtip':{'project':[],'floor':[],'bdr':[],'device_name':[],'mgtip':[],'mgtmask':[]},'connect':{'project':[],'A_floor':[],'A_bdr':[],'A_device':[],'A_port':[],'A_ip':[],'Z_floor':[],'Z_bdr':[],'Z_device':[],'Z_port':[],'Z_ip':[]}}

#核心链接关系
    connection_dict['connect']['project'].append(project)
    connection_dict['connect']['A_floor'].append(coa_info.get_coa_info(project)['floor'])
    connection_dict['connect']['A_bdr'].append(coa_info.get_coa_info(project)['bdr'])
    connection_dict['connect']['A_device'].append(coa_info.get_coa_info(project)['MCOA'])
    connection_dict['connect']['A_port'].append(coa_info.get_coa_info(project)['port_assign']['interconnect'][0])
    connection_dict['connect']['A_ip'].append('Trunk')
    connection_dict['connect']['A_floor'].append(coa_info.get_coa_info(project)['floor'])
    connection_dict['connect']['A_bdr'].append(coa_info.get_coa_info(project)['bdr'])
    connection_dict['connect']['A_device'].append(coa_info.get_coa_info(project)['MCOA'])
    connection_dict['connect']['A_port'].append(coa_info.get_coa_info(project)['port_assign']['interconnect'][1])
    connection_dict['connect']['A_ip'].append('Trunk')
    connection_dict['connect']['project'].append(project)
    connection_dict['connect']['Z_floor'].append(coa_info.get_coa_info(project)['floor'])
    connection_dict['connect']['Z_bdr'].append(coa_info.get_coa_info(project)['bdr'])
    connection_dict['connect']['Z_device'].append(coa_info.get_coa_info(project)['SCOA'])
    connection_dict['connect']['Z_port'].append(coa_info.get_coa_info(project)['port_assign']['interconnect'][0])
    connection_dict['connect']['Z_ip'].append('Trunk')
    connection_dict['connect']['Z_floor'].append(coa_info.get_coa_info(project)['floor'])
    connection_dict['connect']['Z_bdr'].append(coa_info.get_coa_info(project)['bdr'])
    connection_dict['connect']['Z_device'].append(coa_info.get_coa_info(project)['SCOA'])
    connection_dict['connect']['Z_port'].append(coa_info.get_coa_info(project)['port_assign']['interconnect'][1])
    connection_dict['connect']['Z_ip'].append('Trunk')

    func = ip_assign.network_class(network,project)
    connect_ip = func['connection_ip']
    for coa,doa in zip(coa_info.get_coa_info(project)['port_assign']['downlink'],doa_info.get_doa_info(project)):

        d_a_z_ip = connect_ip.__next__()[0]
        connection_dict['connect']['project'].append(project)
        connection_dict['connect']['A_floor'].append(coa_info.get_coa_info(project)['floor'])
        connection_dict['connect']['A_bdr'].append(coa_info.get_coa_info(project)['bdr'])
        connection_dict['connect']['A_device'].append(coa_info.get_coa_info(project)['MCOA'])
        connection_dict['connect']['A_port'].append(coa)
        connection_dict['connect']['A_ip'].append(d_a_z_ip[1])
        connection_dict['connect']['Z_floor'].append(doa['DDOA']['floor'])
        connection_dict['connect']['Z_bdr'].append(doa['DDOA']['bdr'])
        connection_dict['connect']['Z_device'].append(doa['DDOA']['name'])
        connection_dict['connect']['Z_port'].append(doa['DDOA']['port_assign']['uplink'][0])
        connection_dict['connect']['Z_ip'].append(d_a_z_ip[2])

        e_a_z_ip = connect_ip.__next__()[0]
        connection_dict['connect']['project'].append(project)
        connection_dict['connect']['A_floor'].append(coa_info.get_coa_info(project)['floor'])
        connection_dict['connect']['A_bdr'].append(coa_info.get_coa_info(project)['bdr'])
        connection_dict['connect']['A_device'].append(coa_info.get_coa_info(project)['SCOA'])
        connection_dict['connect']['A_port'].append(coa)
        connection_dict['connect']['A_ip'].append(e_a_z_ip[1])
        connection_dict['connect']['Z_floor'].append(doa['EDOA']['floor'])
        connection_dict['connect']['Z_bdr'].append(doa['EDOA']['bdr'])
        connection_dict['connect']['Z_device'].append(doa['EDOA']['name'])
        connection_dict['connect']['Z_port'].append(doa['EDOA']['port_assign']['uplink'][0])
        connection_dict['connect']['Z_ip'].append(e_a_z_ip[2])

        connection_dict['connect']['project'].append(project)
        connection_dict['connect']['A_floor'].append(doa['DDOA']['floor'])
        connection_dict['connect']['A_bdr'].append(doa['DDOA']['bdr'])
        connection_dict['connect']['A_device'].append(doa['DDOA']['name'])
        connection_dict['connect']['A_port'].append(doa['DDOA']['port_assign']['interconnect'][0])
        connection_dict['connect']['A_ip'].append('Trunk')
        connection_dict['connect']['Z_floor'].append(doa['EDOA']['floor'])
        connection_dict['connect']['Z_bdr'].append(doa['EDOA']['bdr'])
        connection_dict['connect']['Z_device'].append(doa['EDOA']['name'])
        connection_dict['connect']['Z_port'].append(doa['EDOA']['port_assign']['interconnect'][0])
        connection_dict['connect']['Z_ip'].append('Trunk')

        connection_dict['connect']['project'].append(project)
        connection_dict['connect']['A_floor'].append(doa['DDOA']['floor'])
        connection_dict['connect']['A_bdr'].append(doa['DDOA']['bdr'])
        connection_dict['connect']['A_device'].append(doa['DDOA']['name'])
        connection_dict['connect']['A_port'].append(doa['DDOA']['port_assign']['interconnect'][1])
        connection_dict['connect']['A_ip'].append('Trunk')
        connection_dict['connect']['Z_floor'].append(doa['EDOA']['floor'])
        connection_dict['connect']['Z_bdr'].append(doa['EDOA']['bdr'])
        connection_dict['connect']['Z_device'].append(doa['EDOA']['name'])
        connection_dict['connect']['Z_port'].append(doa['EDOA']['port_assign']['interconnect'][1])
        connection_dict['connect']['Z_ip'].append('Trunk')

#接入到汇聚互联/管理IP
    for doa,xoa in zip(doa_info.get_doa_info(project), access_info.get_access_info(project)):
        # connection_dict['connect']['Z_floor'].append(doa['DDOA']['floor'])
        # connection_dict['connect']['Z_bdr'].append(doa['DDOA']['bdr'])
        connection_dict['mgtip']['project'].append(project)
        connection_dict['mgtip']['floor'].append(doa['DDOA']['floor'])
        connection_dict['mgtip']['bdr'].append(doa['DDOA']['bdr'])
        connection_dict['mgtip']['device_name'].append(doa['DDOA']['name'])
        connection_dict['mgtip']['mgtip'].append(doa['DDOA']['mgtip'])
        connection_dict['mgtip']['mgtmask'].append(doa['DDOA']['netmask'])
        connection_dict['mgtip']['project'].append(project)
        connection_dict['mgtip']['floor'].append(doa['EDOA']['floor'])
        connection_dict['mgtip']['bdr'].append(doa['EDOA']['bdr'])
        connection_dict['mgtip']['device_name'].append(doa['EDOA']['name'])
        connection_dict['mgtip']['mgtip'].append(doa['EDOA']['mgtip'])
        connection_dict['mgtip']['mgtmask'].append(doa['EDOA']['netmask'])
        for dname in xoa['DXOA']:
            connection_dict['mgtip']['project'].append(project)
            connection_dict['mgtip']['floor'].append(dname['floor'])
            connection_dict['mgtip']['bdr'].append(dname['bdr'])
            connection_dict['mgtip']['device_name'].append(dname['name'])
            connection_dict['mgtip']['mgtip'].append(dname['ip'])
            connection_dict['mgtip']['mgtmask'].append(dname['netmask'])


            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['DDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['DDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['DDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['DDOA']['port_assign']['ddownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(dname['floor'])
            connection_dict['connect']['Z_bdr'].append(dname['bdr'])
            connection_dict['connect']['Z_device'].append(dname['name'])
            connection_dict['connect']['Z_port'].append(dname['port_assign'][0])
            connection_dict['connect']['Z_ip'].append('Trunk')
            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['EDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['EDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['EDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['EDOA']['port_assign']['ddownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(dname['floor'])
            connection_dict['connect']['Z_bdr'].append(dname['bdr'])
            connection_dict['connect']['Z_device'].append(dname['name'])
            connection_dict['connect']['Z_port'].append(dname['port_assign'][1])
            connection_dict['connect']['Z_ip'].append('Trunk')
        for ename in xoa['EXOA']:
            # mgt_sheet.append([ename['name'], ename['ip'], ename['netmask']])
            connection_dict['mgtip']['project'].append(project)
            connection_dict['mgtip']['floor'].append(ename['floor'])
            connection_dict['mgtip']['bdr'].append(ename['bdr'])
            connection_dict['mgtip']['device_name'].append(ename['name'])
            connection_dict['mgtip']['mgtip'].append(ename['ip'])
            connection_dict['mgtip']['mgtmask'].append(ename['netmask'])
            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['DDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['DDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['DDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['DDOA']['port_assign']['edownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(ename['floor'])
            connection_dict['connect']['Z_bdr'].append(ename['bdr'])
            connection_dict['connect']['Z_device'].append(ename['name'])
            connection_dict['connect']['Z_port'].append(ename['port_assign'][0])
            connection_dict['connect']['Z_ip'].append('Trunk')
            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['EDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['EDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['EDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['EDOA']['port_assign']['edownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(ename['floor'])
            connection_dict['connect']['Z_bdr'].append(ename['bdr'])
            connection_dict['connect']['Z_device'].append(ename['name'])
            connection_dict['connect']['Z_port'].append(ename['port_assign'][1])
            connection_dict['connect']['Z_ip'].append('Trunk')
        for vname in xoa['VEVP']:
            connection_dict['mgtip']['project'].append(project)
            connection_dict['mgtip']['floor'].append(vname['floor'])
            connection_dict['mgtip']['bdr'].append(vname['bdr'])
            connection_dict['mgtip']['device_name'].append(vname['name'])
            connection_dict['mgtip']['mgtip'].append(vname['ip'])
            connection_dict['mgtip']['mgtmask'].append(vname['netmask'])
            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['DDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['DDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['DDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['DDOA']['port_assign']['vdownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(vname['floor'])
            connection_dict['connect']['Z_bdr'].append(vname['bdr'])
            connection_dict['connect']['Z_device'].append(vname['name'])
            connection_dict['connect']['Z_port'].append(vname['port_assign'][0])
            connection_dict['connect']['Z_ip'].append('Trunk')
            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['EDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['EDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['EDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['EDOA']['port_assign']['vdownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(vname['floor'])
            connection_dict['connect']['Z_bdr'].append(vname['bdr'])
            connection_dict['connect']['Z_device'].append(vname['name'])
            connection_dict['connect']['Z_port'].append(vname['port_assign'][1])
            connection_dict['connect']['Z_ip'].append('Trunk')
        for wname in xoa['VEWL']:
            connection_dict['mgtip']['project'].append(project)
            connection_dict['mgtip']['floor'].append(wname['floor'])
            connection_dict['mgtip']['bdr'].append(wname['bdr'])
            connection_dict['mgtip']['device_name'].append(wname['name'])
            connection_dict['mgtip']['mgtip'].append(wname['ip'])
            connection_dict['mgtip']['mgtmask'].append(wname['netmask'])
            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['DDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['DDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['DDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['DDOA']['port_assign']['wdownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(wname['floor'])
            connection_dict['connect']['Z_bdr'].append(wname['bdr'])
            connection_dict['connect']['Z_device'].append(wname['name'])
            connection_dict['connect']['Z_port'].append(wname['port_assign'][0])
            connection_dict['connect']['Z_ip'].append('Trunk')
            connection_dict['connect']['project'].append(project)
            connection_dict['connect']['A_floor'].append(doa['EDOA']['floor'])
            connection_dict['connect']['A_bdr'].append(doa['EDOA']['bdr'])
            connection_dict['connect']['A_device'].append(doa['EDOA']['name'])
            connection_dict['connect']['A_port'].append((doa['EDOA']['port_assign']['wdownlink']).pop(0))
            connection_dict['connect']['A_ip'].append('Trunk')
            connection_dict['connect']['Z_floor'].append(wname['floor'])
            connection_dict['connect']['Z_bdr'].append(wname['bdr'])
            connection_dict['connect']['Z_device'].append(wname['name'])
            connection_dict['connect']['Z_port'].append(wname['port_assign'][1])
            connection_dict['connect']['Z_ip'].append('Trunk')

    return connection_dict